{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "delivery-mgmt-svc.serviceAccountName" . }}
  labels:
{{ include "delivery-mgmt-svc.labels" . | indent 4 }}
{{- end -}}
